title: Yuhan Wang
description: Academic personal website
url: "https://hanhuangv587.github.io"
baseurl: ""
lang: en

author:
  name: Yuhan Wang
  role: Graduate Researcher in Agricultural and Applied Economics
  affiliation: University of Wisconsin - Madison
  email: ywang2558@wisc.edu
  location: Madison, WI
  github: hanhuangv587
  linkedin: ""
  scholar: ""

nav:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Teaching
    url: /teaching/
  - title: CV
    url: /cv/
  - title: Data
    url: /data/

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
